name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.25.x]
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...
      
      - name: Test
        run: go test -v ./...