name: Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
        
      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/filego/ecowitt2mqtt:latest
          docker push ghcr.io/filego/ecowitt2mqtt:latest

